### ISSUE TITLE
Feature proposal: it could work on multiple files at once instead just on current file

### ISSUE THREAD

**Issue by fogine** [thinca/vim-qfreplace#11]
When I call `:Qfreplace` it seems that it operates only on current file, which is already great! but It would be really helpful if `Qfreplace` could run on data which has been already placed to `quikfix` window by another command and take into an account`path/to/file|30 col 51|` -> file location header on each line in `quikfix` window, when replacing results in window of type `qfreplace`.

**Comment by thinca** [comment]
It is already available.
